# Generated by Django 5.0.6 on 2025-03-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Ф.И.О')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('workplace', models.CharField(max_length=255, verbose_name='Место работы')),
                ('academic_degree', models.CharField(blank=True, max_length=255, null=True, verbose_name='Научная степень')),
                ('thesis_title', models.CharField(max_length=500, verbose_name='Название тезиса')),
            ],
        ),
    ]
